export const POPULAR_MOVIES = {
    POPULAR_MOVIES_FETCH_REQUEST: "POPULAR_MOVIES_FETCH_REQUEST",
    POPULAR_MOVIES_FETCH_SUCCEEDED: "POPULAR_MOVIES_FETCH_SUCCEEDED",
    POPULAR_MOVIES_FETCH_FAILED: "POPULAR_MOVIES_FETCH_FAILED"
};

export const fetchPopularMovies = () => ({
    type: POPULAR_MOVIES.POPULAR_MOVIES_FETCH_REQUEST
});
