export const TOP_MOVIES = {
    TOP_MOVIES_FETCH_SUCCEEDED: "TOP_MOVIES_FETCH_SUCCEEDED",
    TOP_MOVIES_FETCH_REQUEST: "TOP_MOVIES_FETCH_REQUEST",
    TOP_MOVIES_FETCH_FAILED: "TOP_MOVIES_FETCH_FAILED",
    INFO_ABOUT_MOVIE_FETCH_FAILED: "INFO_ABOUT_MOVIE_FETCH_FAILED"
};

export const fetchTopMovies = () => ({
    type: TOP_MOVIES.TOP_MOVIES_FETCH_REQUEST
});
