export const ACTORS = {
    ACTORS_FETCH_REQUEST: "ACTORS_FETCH_REQUEST",
    ACTORS_FETCH_SUCCEEDED: "ACTORS_FETCH_SUCCEEDED",
    ACTORS_FETCH_FAILED: "ACTORS_FETCH_FAILED"
};

export const fetchActorsList = () => ({
    type: ACTORS.ACTORS_FETCH_REQUEST
});
